/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistenciaTecnicaRouteImport } from './routes/assistencia-tecnica'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as VendaSeuIphoneRouteImport } from './routes/venda-seu-iphone'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as AdminContratosIndexRouteImport } from './routes/admin.contratos.index'
import { Route as AdminContratosConfiguracaoRouteImport } from './routes/admin.contratos.configuracao'
import { Route as AdminContratosNovoRouteImport } from './routes/admin.contratos.novo'
import { Route as AdminDossiesIndexRouteImport } from './routes/admin.dossies.index'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as AdminContratosIdIndexRouteImport } from './routes/admin.contratos.$id.index'
import { Route as AdminContratosIdPreencherRouteImport } from './routes/admin.contratos.$id.preencher'
import { Route as AdminDossiesIdIndexRouteImport } from './routes/admin.dossies.$id.index'
import { Route as AdminDossiesIdEtiquetaRouteImport } from './routes/admin.dossies.$id.etiqueta'
import { Route as AdminProdutosIdEditarRouteImport } from './routes/admin.produtos.$id.editar'
import { Route as ApiPublicFotoSplatRouteImport } from './routes/api/public/foto.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenciaTecnicaRoute = AssistenciaTecnicaRouteImport.update({
  id: '/assistencia-tecnica',
  path: '/assistencia-tecnica',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const VendaSeuIphoneRoute = VendaSeuIphoneRouteImport.update({
  id: '/venda-seu-iphone',
  path: '/venda-seu-iphone',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContratosIndexRoute = AdminContratosIndexRouteImport.update({
  id: '/admin/contratos/',
  path: '/admin/contratos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContratosConfiguracaoRoute =
  AdminContratosConfiguracaoRouteImport.update({
    id: '/admin/contratos/configuracao',
    path: '/admin/contratos/configuracao',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContratosNovoRoute = AdminContratosNovoRouteImport.update({
  id: '/admin/contratos/novo',
  path: '/admin/contratos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDossiesIndexRoute = AdminDossiesIndexRouteImport.update({
  id: '/admin/dossies/',
  path: '/admin/dossies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/admin/produtos/novo',
  path: '/admin/produtos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContratosIdIndexRoute = AdminContratosIdIndexRouteImport.update({
  id: '/admin/contratos/$id/',
  path: '/admin/contratos/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContratosIdPreencherRoute =
  AdminContratosIdPreencherRouteImport.update({
    id: '/admin/contratos/$id/preencher',
    path: '/admin/contratos/$id/preencher',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDossiesIdIndexRoute = AdminDossiesIdIndexRouteImport.update({
  id: '/admin/dossies/$id/',
  path: '/admin/dossies/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDossiesIdEtiquetaRoute = AdminDossiesIdEtiquetaRouteImport.update({
  id: '/admin/dossies/$id/etiqueta',
  path: '/admin/dossies/$id/etiqueta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosIdEditarRoute = AdminProdutosIdEditarRouteImport.update({
  id: '/admin/produtos/$id/editar',
  path: '/admin/produtos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFotoSplatRoute = ApiPublicFotoSplatRouteImport.update({
  id: '/api/public/foto/$',
  path: '/api/public/foto/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistencia-tecnica': typeof AssistenciaTecnicaRoute
  '/entrar': typeof EntrarRoute
  '/minha-conta': typeof MinhaContaRoute
  '/venda-seu-iphone': typeof VendaSeuIphoneRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/login': typeof AdminLoginRoute
  '/d/$token': typeof DTokenRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/contratos/configuracao': typeof AdminContratosConfiguracaoRoute
  '/admin/contratos/novo': typeof AdminContratosNovoRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/dossies/': typeof AdminDossiesIndexRoute
  '/admin/contratos/$id/preencher': typeof AdminContratosIdPreencherRoute
  '/admin/dossies/$id/etiqueta': typeof AdminDossiesIdEtiquetaRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
  '/admin/contratos/$id/': typeof AdminContratosIdIndexRoute
  '/admin/dossies/$id/': typeof AdminDossiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistencia-tecnica': typeof AssistenciaTecnicaRoute
  '/entrar': typeof EntrarRoute
  '/minha-conta': typeof MinhaContaRoute
  '/venda-seu-iphone': typeof VendaSeuIphoneRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/login': typeof AdminLoginRoute
  '/d/$token': typeof DTokenRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/admin/contratos/configuracao': typeof AdminContratosConfiguracaoRoute
  '/admin/contratos/novo': typeof AdminContratosNovoRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/contratos': typeof AdminContratosIndexRoute
  '/admin/dossies': typeof AdminDossiesIndexRoute
  '/admin/contratos/$id/preencher': typeof AdminContratosIdPreencherRoute
  '/admin/dossies/$id/etiqueta': typeof AdminDossiesIdEtiquetaRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
  '/admin/contratos/$id': typeof AdminContratosIdIndexRoute
  '/admin/dossies/$id': typeof AdminDossiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistencia-tecnica': typeof AssistenciaTecnicaRoute
  '/entrar': typeof EntrarRoute
  '/minha-conta': typeof MinhaContaRoute
  '/venda-seu-iphone': typeof VendaSeuIphoneRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/login': typeof AdminLoginRoute
  '/d/$token': typeof DTokenRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/contratos/configuracao': typeof AdminContratosConfiguracaoRoute
  '/admin/contratos/novo': typeof AdminContratosNovoRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/dossies/': typeof AdminDossiesIndexRoute
  '/admin/contratos/$id/preencher': typeof AdminContratosIdPreencherRoute
  '/admin/dossies/$id/etiqueta': typeof AdminDossiesIdEtiquetaRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
  '/api/public/foto/$': typeof ApiPublicFotoSplatRoute
  '/admin/contratos/$id/': typeof AdminContratosIdIndexRoute
  '/admin/dossies/$id/': typeof AdminDossiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistencia-tecnica'
    | '/entrar'
    | '/minha-conta'
    | '/venda-seu-iphone'
    | '/admin/clientes'
    | '/admin/login'
    | '/d/$token'
    | '/produtos/$slug'
    | '/admin/'
    | '/produtos/'
    | '/admin/contratos/configuracao'
    | '/admin/contratos/novo'
    | '/admin/produtos/novo'
    | '/admin/contratos/'
    | '/admin/dossies/'
    | '/admin/contratos/$id/preencher'
    | '/admin/dossies/$id/etiqueta'
    | '/admin/produtos/$id/editar'
    | '/api/public/foto/$'
    | '/admin/contratos/$id/'
    | '/admin/dossies/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistencia-tecnica'
    | '/entrar'
    | '/minha-conta'
    | '/venda-seu-iphone'
    | '/admin/clientes'
    | '/admin/login'
    | '/d/$token'
    | '/produtos/$slug'
    | '/admin'
    | '/produtos'
    | '/admin/contratos/configuracao'
    | '/admin/contratos/novo'
    | '/admin/produtos/novo'
    | '/admin/contratos'
    | '/admin/dossies'
    | '/admin/contratos/$id/preencher'
    | '/admin/dossies/$id/etiqueta'
    | '/admin/produtos/$id/editar'
    | '/api/public/foto/$'
    | '/admin/contratos/$id'
    | '/admin/dossies/$id'
  id:
    | '__root__'
    | '/'
    | '/assistencia-tecnica'
    | '/entrar'
    | '/minha-conta'
    | '/venda-seu-iphone'
    | '/admin/clientes'
    | '/admin/login'
    | '/d/$token'
    | '/produtos/$slug'
    | '/admin/'
    | '/produtos/'
    | '/admin/contratos/configuracao'
    | '/admin/contratos/novo'
    | '/admin/produtos/novo'
    | '/admin/contratos/'
    | '/admin/dossies/'
    | '/admin/contratos/$id/preencher'
    | '/admin/dossies/$id/etiqueta'
    | '/admin/produtos/$id/editar'
    | '/api/public/foto/$'
    | '/admin/contratos/$id/'
    | '/admin/dossies/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenciaTecnicaRoute: typeof AssistenciaTecnicaRoute
  EntrarRoute: typeof EntrarRoute
  MinhaContaRoute: typeof MinhaContaRoute
  VendaSeuIphoneRoute: typeof VendaSeuIphoneRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DTokenRoute: typeof DTokenRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
  AdminContratosConfiguracaoRoute: typeof AdminContratosConfiguracaoRoute
  AdminContratosNovoRoute: typeof AdminContratosNovoRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminContratosIndexRoute: typeof AdminContratosIndexRoute
  AdminDossiesIndexRoute: typeof AdminDossiesIndexRoute
  AdminContratosIdPreencherRoute: typeof AdminContratosIdPreencherRoute
  AdminDossiesIdEtiquetaRoute: typeof AdminDossiesIdEtiquetaRoute
  AdminProdutosIdEditarRoute: typeof AdminProdutosIdEditarRoute
  ApiPublicFotoSplatRoute: typeof ApiPublicFotoSplatRoute
  AdminContratosIdIndexRoute: typeof AdminContratosIdIndexRoute
  AdminDossiesIdIndexRoute: typeof AdminDossiesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistencia-tecnica': {
      id: '/assistencia-tecnica'
      path: '/assistencia-tecnica'
      fullPath: '/assistencia-tecnica'
      preLoaderRoute: typeof AssistenciaTecnicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venda-seu-iphone': {
      id: '/venda-seu-iphone'
      path: '/venda-seu-iphone'
      fullPath: '/venda-seu-iphone'
      preLoaderRoute: typeof VendaSeuIphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contratos/': {
      id: '/admin/contratos/'
      path: '/admin/contratos'
      fullPath: '/admin/contratos/'
      preLoaderRoute: typeof AdminContratosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contratos/configuracao': {
      id: '/admin/contratos/configuracao'
      path: '/admin/contratos/configuracao'
      fullPath: '/admin/contratos/configuracao'
      preLoaderRoute: typeof AdminContratosConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contratos/novo': {
      id: '/admin/contratos/novo'
      path: '/admin/contratos/novo'
      fullPath: '/admin/contratos/novo'
      preLoaderRoute: typeof AdminContratosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dossies/': {
      id: '/admin/dossies/'
      path: '/admin/dossies'
      fullPath: '/admin/dossies/'
      preLoaderRoute: typeof AdminDossiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/admin/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contratos/$id/': {
      id: '/admin/contratos/$id/'
      path: '/admin/contratos/$id'
      fullPath: '/admin/contratos/$id/'
      preLoaderRoute: typeof AdminContratosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contratos/$id/preencher': {
      id: '/admin/contratos/$id/preencher'
      path: '/admin/contratos/$id/preencher'
      fullPath: '/admin/contratos/$id/preencher'
      preLoaderRoute: typeof AdminContratosIdPreencherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dossies/$id/': {
      id: '/admin/dossies/$id/'
      path: '/admin/dossies/$id'
      fullPath: '/admin/dossies/$id/'
      preLoaderRoute: typeof AdminDossiesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dossies/$id/etiqueta': {
      id: '/admin/dossies/$id/etiqueta'
      path: '/admin/dossies/$id/etiqueta'
      fullPath: '/admin/dossies/$id/etiqueta'
      preLoaderRoute: typeof AdminDossiesIdEtiquetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos/$id/editar': {
      id: '/admin/produtos/$id/editar'
      path: '/admin/produtos/$id/editar'
      fullPath: '/admin/produtos/$id/editar'
      preLoaderRoute: typeof AdminProdutosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/foto/$': {
      id: '/api/public/foto/$'
      path: '/api/public/foto/$'
      fullPath: '/api/public/foto/$'
      preLoaderRoute: typeof ApiPublicFotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenciaTecnicaRoute: AssistenciaTecnicaRoute,
  EntrarRoute: EntrarRoute,
  MinhaContaRoute: MinhaContaRoute,
  VendaSeuIphoneRoute: VendaSeuIphoneRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminLoginRoute: AdminLoginRoute,
  DTokenRoute: DTokenRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
  AdminContratosConfiguracaoRoute: AdminContratosConfiguracaoRoute,
  AdminContratosNovoRoute: AdminContratosNovoRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminContratosIndexRoute: AdminContratosIndexRoute,
  AdminDossiesIndexRoute: AdminDossiesIndexRoute,
  AdminContratosIdPreencherRoute: AdminContratosIdPreencherRoute,
  AdminDossiesIdEtiquetaRoute: AdminDossiesIdEtiquetaRoute,
  AdminProdutosIdEditarRoute: AdminProdutosIdEditarRoute,
  ApiPublicFotoSplatRoute: ApiPublicFotoSplatRoute,
  AdminContratosIdIndexRoute: AdminContratosIdIndexRoute,
  AdminDossiesIdIndexRoute: AdminDossiesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
